rabbitMQUrl: "amqp://chenglongcl:123456@localhost:5672/"
rabbitMQDefaultExchange: exch.unitest
rabbitMQBindings:
- routeKey: route.unitest1
  queue: queue.unitest1
- routeKey: route.unitest2
  queue: queue.unitest2
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/consumer.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 10240
  log_backup_count: 7