// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package apiservermodel

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTbUser = "tb_user"

// TbUser mapped from table <tb_user>
type TbUser struct {
	ID        uint64         `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Username  string         `gorm:"column:username;type:varchar(255);not null" json:"username"` // 用户名
	Password  string         `gorm:"column:password;type:varchar(255);not null" json:"password"` // 密码
	Mobile    string         `gorm:"column:mobile;type:varchar(255);not null" json:"mobile"`
	Status    bool           `gorm:"column:status;type:tinyint(1);not null" json:"status"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:timestamp" json:"createdAt"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp" json:"updatedAt"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deletedAt"`
}

// TableName TbUser's table name
func (*TbUser) TableName() string {
	return TableNameTbUser
}
