// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package apiservermodel

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTbUserToken = "tb_user_token"

// TbUserToken mapped from table <tb_user_token>
type TbUserToken struct {
	UserID      uint64         `gorm:"column:user_id;type:int(11) unsigned;primaryKey" json:"userID"`
	Token       string         `gorm:"column:token;type:varchar(255);not null" json:"token"` // token
	ExpireTime  *time.Time     `gorm:"column:expire_time;type:datetime" json:"expireTime"`   // 过期时间
	RefreshTime *time.Time     `gorm:"column:refresh_time;type:datetime" json:"refreshTime"` // 更新时间
	CreatedAt   *time.Time     `gorm:"column:created_at;type:timestamp" json:"createdAt"`    // 创建时间
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:timestamp" json:"updatedAt"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deletedAt"`
}

// TableName TbUserToken's table name
func (*TbUserToken) TableName() string {
	return TableNameTbUserToken
}
