log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 10240
  log_backup_count: 7
db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password: 123456
docker_db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password: 123456